"""init — initialize project with ignore files + AI rules + config."""

from __future__ import annotations

import sys
from pathlib import Path

from rich.console import Console
from rich.panel import Panel
from rich.table import Table
from rich.text import Text

from contextslim.analyzer.stack_detector import detect_stack
from contextslim.generators.ignore import write_ignore
from contextslim.generators.rules import write_rules

console = Console(highlight=False)

_DEFAULT_CONFIG_TOML = """\
# ContextSlim configuration
# Auto-generated by `contextslim setup init`

[limits]
# cat_lines = 150
# grep_matches_per_file = 5
# grep_max_total = 50
# tree_depth = 3
# max_line_width = 120
# outline_max_sigs_per_file = 15
# db_sample_rows = 5
# db_max_columns = 20
# procs_limit = 30
# services_limit = 30
# findfiles_limit = 30
# todo_max_total = 50
"""


def _canonical_stack_name(stack_name: str) -> str:
    """Map detected stack name to a canonical ignore-pattern key."""
    mapping: dict[str, str] = {
        "Node.js": "node",
        "Python": "python",
        "Rust": "rust",
        "Go": "go",
        "Java": "java",
        "Ruby": "ruby",
        "PHP": "php",
        "C#": "csharp",
        "Kotlin": "kotlin",
        "Swift": "swift",
        "Dart": "dart",
        "Elixir": "elixir",
        "Haskell": "haskell",
        "Zig": "zig",
    }
    return mapping.get(stack_name, stack_name.lower())


def init_command(directory: str, ides: list[str], force: bool) -> None:
    """Initialize project with ignore files + AI rules.

    Args:
        directory: Project root directory path.
        ides: List of IDE identifiers (e.g. ["cursor", "claude"]).
        force: If True, overwrite existing .contextslim.toml.
    """
    project_dir = Path(directory).resolve()
    if not project_dir.is_dir():
        console.print(f"[red]Error:[/red] Directory not found: {directory}")
        return

    # Validate IDE list
    valid_ides = {"cursor", "claude", "copilot", "windsurf"}
    filtered_ides = [ide for ide in ides if ide.strip() in valid_ides]
    unknown = [ide for ide in ides if ide.strip() and ide.strip() not in valid_ides]
    if unknown:
        console.print(f"[yellow]Warning:[/yellow] Unknown IDEs ignored: {', '.join(unknown)}")
    if not filtered_ides:
        console.print("[red]Error:[/red] No valid IDEs specified. Use: cursor, claude, copilot, windsurf")
        return

    created: list[str] = []
    updated: list[str] = []
    skipped: list[str] = []

    # 1. Detect stack
    console.print()
    console.print("[bold]ContextSlim — Project Initialization[/bold]")
    console.print(f"Directory: [dim]{project_dir}[/dim]")
    console.print()

    stack = detect_stack(project_dir)
    if stack is None:
        console.print("[yellow]⚠[/yellow] No stack detected. Using generic defaults.")
        stack_name = "Unknown"
        language = "unknown"
        frameworks: list[str] = []
        stack_key = "node"  # generic ignore patterns
    else:
        stack_name = stack.name
        if stack.has_typescript and stack.language == "JavaScript":
            language = "typescript"
            stack_name = f"{stack.name} + TypeScript"
        else:
            language = stack.language.lower()
            if language == "javascript":
                language = "javascript"
        frameworks = stack.frameworks
        console.print(
            f"  Detected: [bold green]{stack_name}[/bold green] "
            f"({language}" + (f", {', '.join(frameworks)}" if frameworks else "") + ")"
        )
        stack_key = _canonical_stack_name(stack.name)
        if stack.detected_files:
            console.print(
                f"  Signal files: [dim]{', '.join(stack.detected_files)}[/dim]"
            )

    # 2. Write .contextslim.toml
    config_path = project_dir / ".contextslim.toml"
    if config_path.exists() and not force:
        console.print(f"  [dim]⊘[/dim] .contextslim.toml already exists (use --force to overwrite)")
        skipped.append(".contextslim.toml")
    else:
        config_path.write_text(_DEFAULT_CONFIG_TOML, encoding="utf-8")
        if config_path.exists() and force:
            updated.append(".contextslim.toml")
        else:
            created.append(".contextslim.toml")

    # 3. Write ignore files
    console.print()
    console.print("[bold]Ignore Files[/bold]")
    ignore_added = write_ignore(project_dir, stack_key)
    gitignore_path = project_dir / ".gitignore"
    if gitignore_path.exists():
        if ignore_added:
            status = f"[green]✓[/green] .gitignore ({len(ignore_added)} new patterns)"
            created.append(".gitignore")
        else:
            status = "[dim]⊘[/dim] .gitignore (all patterns already present)"
            skipped.append(".gitignore")
    console.print(f"  {status}")
    if ignore_added:
        console.print(f"    Added: [dim]{', '.join(ignore_added[:8])}{'...' if len(ignore_added) > 8 else ''}[/dim]")

    # 4. Write AI rules
    console.print()
    console.print("[bold]AI Rules[/bold]")
    rules_written = write_rules(project_dir, filtered_ides, stack_name, language, frameworks)
    for ide, path_str in rules_written.items():
        file_path = Path(path_str)
        rel = file_path.relative_to(project_dir) if project_dir in file_path.parents else file_path
        console.print(f"  [green]✓[/green] {rel}")
        created.append(f"{ide} rules ({rel})")

    # 5. Summary panel
    console.print()

    summary_table = Table(show_header=False, box=None)
    summary_table.add_column("Step", style="dim")
    summary_table.add_column("Result")

    summary_table.add_row(
        "Stack detected", f"{stack_name} ({language})" if stack else "None (generic defaults)"
    )
    summary_table.add_row(
        "Config",
        (
            "[green]Created[/green]"
            if ".contextslim.toml" in created
            else "[yellow]Updated[/yellow]" if ".contextslim.toml" in updated
            else "[dim]Skipped[/dim]"
        ),
    )
    summary_table.add_row(
        "Ignore file",
        (
            "[green]Created[/green]" if ".gitignore" in created
            else "[dim]Skipped[/dim]"
        ),
    )
    summary_table.add_row(
        "AI rules",
        "[green]Created[/green]" if any("rules" in c for c in created)
        else "[dim]None[/dim]",
    )

    panel = Panel(summary_table, title="Setup Complete", border_style="green")
    console.print(panel)
