"""Tests for contextslim.generators.rules — IDE rule generation."""

from __future__ import annotations

from pathlib import Path

import pytest

from contextslim.generators.rules import generate_rules, write_rules


class TestGenerateRules:
    """Unit tests for generate_rules()."""

    def test_returns_all_four_ides_by_default(self) -> None:
        """Given: 4 IDEs. When: generate_rules called. Then: dict has 4 keys."""
        ides = ["cursor", "claude", "copilot", "windsurf"]
        result = generate_rules(ides, "Node.js", "typescript")
        assert set(result.keys()) == set(ides)

    def test_each_ide_content_is_non_empty(self) -> None:
        """Given: each IDE. When: rules generated. Then: content is non-empty."""
        for ide in ["cursor", "claude", "copilot", "windsurf"]:
            result = generate_rules([ide], "Django", "python")
            assert ide in result
            assert len(result[ide]) > 50, f"{ide} content is too short"

    def test_includes_contextslim_command_reference(self) -> None:
        """Given: any IDE. When: rules generated. Then: contextslim commands referenced."""
        result = generate_rules(["cursor"], "Flask", "python")
        content = result["cursor"]
        assert "contextslim" in content.lower()
        assert "contextslim tree" in content.lower()

    def test_includes_language_specific_rules_python(self) -> None:
        """Given: python stack. When: rules generated. Then: Python guidelines present."""
        result = generate_rules(["claude"], "Django", "python")
        content = result["claude"]
        assert "PEP 8" in content
        assert "type hints" in content

    def test_includes_language_specific_rules_typescript(self) -> None:
        """Given: typescript stack. When: rules generated. Then: TS guidelines present."""
        result = generate_rules(["copilot"], "Next.js", "typescript")
        content = result["copilot"]
        assert "TypeScript types" in content
        assert "optional chaining" in content

    def test_includes_language_specific_rules_rust(self) -> None:
        """Given: rust stack. When: rules generated. Then: Rust guidelines present."""
        result = generate_rules(["windsurf"], "Tauri", "rust")
        content = result["windsurf"]
        assert "Result<T, E>" in content
        assert "clippy" in content

    def test_includes_language_specific_rules_go(self) -> None:
        """Given: go stack. When: rules generated. Then: Go guidelines present."""
        result = generate_rules(["cursor"], "CLI Tool", "go")
        content = result["cursor"]
        assert "context.Context" in content

    def test_includes_framework_specific_rules(self) -> None:
        """Given: frameworks list. When: rules generated. Then: framework rules present."""
        result = generate_rules(["claude"], "Web App", "typescript", ["react", "next.js"])
        content = result["claude"]
        assert "App Router" in content
        assert "functional React components" in content
        assert "React.memo" in content

    def test_no_frameworks_no_framework_section(self) -> None:
        """Given: no frameworks. When: rules generated. Then: no framework section."""
        result = generate_rules(["cursor"], "Simple", "python")
        assert "## Frameworks" not in result["cursor"]

    def test_unknown_language_has_header_only(self) -> None:
        """Given: unknown language. When: rules generated. Then: only common header + IDE block."""
        result = generate_rules(["cursor"], "Elixir", "elixir")
        content = result["cursor"]
        assert "Generated by ContextSlim" in content
        assert "Language" not in content  # no language section

    def test_unknown_ide_is_skipped(self) -> None:
        """Given: unknown IDE in list. When: generate_rules called. Then: silently skipped."""
        result = generate_rules(["cursor", "gemini"], "Python Backend", "python")
        assert set(result.keys()) == {"cursor"}

    def test_includes_ide_specific_section(self) -> None:
        """Given: each IDE. When: rules generated. Then: IDE-specific section present."""
        for ide, section_tag in [
            ("cursor", "Cursor Specific"),
            ("claude", "Claude Code Specific"),
            ("copilot", "GitHub Copilot Specific"),
            ("windsurf", "Windsurf Specific"),
        ]:
            result = generate_rules([ide], "Test", "python")
            assert section_tag in result[ide]


class TestWriteRules:
    """Integration tests for write_rules()."""

    def test_writes_file_when_missing(self, tmp_path: Path) -> None:
        """Given: empty project dir. When: write_rules called. Then: .cursorrules created."""
        write_rules(tmp_path, ["cursor"], "Flask API", "python")
        assert (tmp_path / ".cursorrules").exists()

    def test_writes_copilot_to_nested_path(self, tmp_path: Path) -> None:
        """Given: empty project dir. When: write_rules for copilot. Then: .github/copilot-instructions.md created."""
        write_rules(tmp_path, ["copilot"], "Next.js App", "typescript")
        assert (tmp_path / ".github" / "copilot-instructions.md").exists()

    def test_returns_written_paths(self, tmp_path: Path) -> None:
        """Given: 2 IDEs. When: write_rules called. Then: dict maps IDE to written path."""
        written = write_rules(tmp_path, ["cursor", "claude"], "Rust CLI", "rust")
        assert written["cursor"] == str(tmp_path / ".cursorrules")
        assert written["claude"] == str(tmp_path / "CLAUDE.md")

    def test_merges_with_existing_user_file(self, tmp_path: Path) -> None:
        """Given: existing .cursorrules without ContextSlim marker. When: write_rules. Then: appended."""
        existing = tmp_path / ".cursorrules"
        existing.write_text("# User custom rules\n")
        write_rules(tmp_path, ["cursor"], "Go API", "go")
        content = existing.read_text()
        assert "# User custom rules" in content
        assert "Generated by ContextSlim" in content

    def test_overwrites_existing_contextslim_file(self, tmp_path: Path) -> None:
        """Given: existing file with ContextSlim marker. When: write_rules. Then: overwritten."""
        existing = tmp_path / "CLAUDE.md"
        existing.write_text("# AI Rules - Generated by ContextSlim\nold content\n", encoding="utf-8")
        write_rules(tmp_path, ["claude"], "FastAPI", "python")
        content = existing.read_text()
        # Old content replaced by new generation
        assert "old content" not in content
        # Marker still present (re-generated)
        assert "Generated by ContextSlim" in content
        # New stack name is present in re-generated content
        assert "FastAPI" in content

    def test_writes_all_four_ides(self, tmp_path: Path) -> None:
        """Given: all 4 IDEs. When: write_rules. Then: all expected files created."""
        write_rules(tmp_path, ["cursor", "claude", "copilot", "windsurf"], "Full Stack", "typescript")
        assert (tmp_path / ".cursorrules").exists()
        assert (tmp_path / "CLAUDE.md").exists()
        assert (tmp_path / ".github" / "copilot-instructions.md").exists()
        assert (tmp_path / ".windsurfrules").exists()

    def test_none_frameworks_works(self, tmp_path: Path) -> None:
        """Given: frameworks=None. When: write_rules. Then: no framework section written."""
        written = write_rules(tmp_path, ["cursor"], "Simple Script", "python", None)
        content = (tmp_path / ".cursorrules").read_text()
        assert "## Frameworks" not in content
        assert written  # still returns dict
