"""IDE rule generation for ContextSlim.

Generates AI behaviour rules for Cursor, Claude, Copilot, and Windsurf.
Each template includes contextslim command guidance, language-specific
recommendations, and framework-specific guidelines.
"""

from __future__ import annotations

from pathlib import Path

# ── IDE file mappings ──────────────────────────────────────────
_IDE_FILES: dict[str, str] = {
    "cursor": ".cursorrules",
    "claude": "CLAUDE.md",
    "copilot": ".github/copilot-instructions.md",
    "windsurf": ".windsurfrules",
}

# ── Language-specific recommendations ───────────────────────────
_LANG_RULES: dict[str, list[str]] = {
    "python": [
        "Use type hints for all function signatures.",
        "Follow PEP 8 style conventions.",
        "Prefer pathlib over os.path for file operations.",
        "Use async/await with anyio (not bare asyncio) for async code.",
    ],
    "typescript": [
        "Use explicit TypeScript types for function parameters and return values.",
        "Prefer interface for object shapes, type for unions/intersections.",
        "Avoid any — use unknown when the type is truly uncertain.",
        "Use async/await over raw Promises or callbacks.",
        "Use optional chaining (?.) and nullish coalescing (??).",
    ],
    "javascript": [
        "Prefer const over let. Never use var.",
        "Use ES Modules (import/export), not CommonJS (require).",
        "Use async/await over raw Promises or callbacks.",
        "Use optional chaining (?.) and nullish coalescing (??).",
    ],
    "rust": [
        "Follow Rust idioms: use Result<T, E> for error handling.",
        "Minimize .unwrap() and .expect() — propagate errors with ?.",
        "Use cargo fmt and cargo clippy before committing.",
    ],
    "go": [
        "Follow Go conventions: explicitly handle errors.",
        "Use context.Context for cancellation and timeouts.",
        "Run gofumpt and golangci-lint before committing.",
    ],
}

# ── Framework-specific recommendations ──────────────────────────
_FRAMEWORK_RULES: dict[str, list[str]] = {
    "react": [
        "Write functional React components using hooks.",
        "Keep effect dependencies accurate.",
        "Use React.memo and useMemo for expensive computations.",
    ],
    "next.js": [
        "Follow Next.js App Router conventions (page.tsx, layout.tsx).",
        "Use server components by default; mark client components explicitly.",
        "Leverage Next.js built-in image and font optimizations.",
    ],
    "vue": [
        "Use Vue 3 Composition API with <script setup>.",
        "Prefer ref() and reactive() for state management.",
        "Use defineProps and defineEmits with TypeScript types.",
    ],
    "nuxt": [
        "Follow Nuxt auto-import conventions for composables and components.",
        "Use server/ directory for API routes, composables/ for shared logic.",
    ],
    "fastapi": [
        "Use Pydantic v2 models for request/response schemas.",
        "Leverage FastAPI dependency injection for shared logic.",
        "Use HTTPException for error responses with proper status codes.",
    ],
    "django": [
        "Follow Django's MVT pattern: Models, Views, Templates.",
        "Use Django ORM query methods, avoid raw SQL when possible.",
        "Keep business logic in models or services, not views.",
    ],
    "flask": [
        "Use Flask blueprints for modular route organization.",
        "Leverage Flask extensions (Flask-SQLAlchemy, Flask-Migrate).",
        "Use application factories for testability.",
    ],
}

# ── Common rule header (all IDEs) ───────────────────────────────
def _build_common_header(
    stack_name: str,
    language_name: str,
    framework_names: list[str],
) -> str:
    """Build the shared rules header for all IDE templates."""
    lines: list[str] = [
        "# AI Rules — Generated by ContextSlim",
        "",
        f"**Stack:** {stack_name} ({language_name})",
    ]
    if framework_names:
        lines.append(f"**Frameworks:** {', '.join(framework_names)}")
    lines.extend([
        "",
        "## Token Optimization",
        "",
        "- Use `contextslim` commands for token-efficient output: "
        "`contextslim tree` instead of `tree`, "
        "`contextslim grep` instead of `grep`, "
        "`contextslim cat` instead of `cat`, "
        "`contextslim map` for file signatures.",
        "- Read only the necessary context. Do not read entire directories "
        "or large lockfiles unless explicitly requested.",
        "- Never read `node_modules/`, `dist/`, `build/`, `.git/`, "
        "`coverage/`, `venv/`, `vendor/`.",
        "",
    ])
    return "\n".join(lines)


def _build_language_section(language_name: str) -> str:
    """Build the language-specific recommendations section."""
    rules = _LANG_RULES.get(language_name.lower(), [])
    if not rules:
        return ""
    lines = [f"## Language: {language_name}", ""]
    for rule in rules:
        lines.append(f"- {rule}")
    lines.append("")
    return "\n".join(lines)


def _build_framework_section(framework_names: list[str]) -> str:
    """Build the framework-specific recommendations section."""
    if not framework_names:
        return ""
    lines = ["## Frameworks", ""]
    for fw in framework_names:
        rules = _FRAMEWORK_RULES.get(fw.lower(), [])
        if rules:
            lines.append(f"### {fw}")
            for rule in rules:
                lines.append(f"- {rule}")
            lines.append("")
    return "\n".join(lines)


def _build_ide_specific(ide: str) -> str:
    """Build IDE-specific guidance block."""
    sections: dict[str, str] = {
        "cursor": (
            "## Cursor Specific\n\n"
            "- Use codebase indexing effectively; do not brute-force read files.\n"
            "- Verify types and lint rules before providing a code block.\n"
            "- Use the Composer for multi-file edits when appropriate.\n"
        ),
        "claude": (
            "## Claude Code Specific\n\n"
            "- Provide code edits without outputting the entire file.\n"
            "- Avoid rambling explanations before writing code.\n"
            "- Stay in character as a senior developer maintaining this exact stack.\n"
        ),
        "copilot": (
            "## GitHub Copilot Specific\n\n"
            "- Provide concise, working code completions.\n"
            "- Follow the project's existing patterns and conventions.\n"
            "- Use `@workspace` agents when context is spread across files.\n"
        ),
        "windsurf": (
            "## Windsurf Specific\n\n"
            "- Leverage Cascade for multi-step reasoning across files.\n"
            "- Use the AI flow panel for reviewing context before edits.\n"
            "- Keep responses focused on the requested change.\n"
        ),
    }
    return sections.get(ide, "")


def generate_rules(
    ides: list[str],
    stack_name: str,
    stack_language: str,
    frameworks: list[str] | None = None,
) -> dict[str, str]:
    """Generate AI rules for each IDE.

    Args:
        ides: Target IDEs (e.g. ["cursor", "claude", "copilot", "windsurf"]).
        stack_name: Display name of the stack (e.g. "Node.js + TypeScript").
        stack_language: Primary language (e.g. "python", "typescript").
        frameworks: List of framework names (e.g. ["react", "next.js"]).

    Returns:
        Dict mapping IDE name to its full rules content string.
    """
    framework_names = frameworks or []
    result: dict[str, str] = {}

    for ide in ides:
        if ide not in _IDE_FILES:
            continue  # silently skip unknown IDEs
        parts: list[str] = [
            _build_common_header(stack_name, stack_language, framework_names),
            _build_language_section(stack_language),
            _build_framework_section(framework_names),
            _build_ide_specific(ide),
        ]
        result[ide] = "".join(parts)

    return result


def write_rules(
    project_dir: Path,
    ides: list[str],
    stack_name: str,
    stack_language: str,
    frameworks: list[str] | None = None,
) -> dict[str, str]:
    """Write rule files to the project directory.

    Merges with existing files if they don't already contain the ContextSlim
    header. Overwrites files that were previously generated by ContextSlim.

    Args:
        project_dir: Root directory of the target project.
        ides: Target IDEs to generate rules for.
        stack_name: Display name of the stack.
        stack_language: Primary language.
        frameworks: List of framework names.

    Returns:
        Dict mapping IDE name to the file path where rules were written.
    """
    framework_names = frameworks or []
    rules = generate_rules(ides, stack_name, stack_language, framework_names)
    written: dict[str, str] = {}

    marker = "Generated by ContextSlim"

    for ide, content in rules.items():
        filename = _IDE_FILES[ide]
        filepath = project_dir / filename
        filepath.parent.mkdir(parents=True, exist_ok=True)

        existing = ""
        if filepath.exists():
            existing = filepath.read_text(encoding="utf-8")

        if not existing:
            filepath.write_text(content, encoding="utf-8")
        elif marker in existing:
            # Re-generate: overwrite the section
            filepath.write_text(content, encoding="utf-8")
        else:
            # User file without our marker: append
            filepath.write_text(existing.rstrip() + "\n\n" + content, encoding="utf-8")

        written[ide] = str(filepath)

    return written
